// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/LayOut/account.vue')['default']
    Aside: typeof import('./src/components/LayOut/Aside.vue')['default']
    BasicModal: typeof import('./src/components/Modal/BasicModal.vue')['default']
    BasicModel: typeof import('./src/components/Model/BasicModel.vue')['default']
    Footer: typeof import('./src/components/LayOut/Footer.vue')['default']
    FooterContorl: typeof import('./src/components/LayOut/FooterContorl.vue')['default']
    FooterControl: typeof import('./src/components/LayOut/FooterControl.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/LayOut/main.vue')['default']
    MainContent: typeof import('./src/components/LayOut/MainContent.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavBar: typeof import('./src/components/LayOut/NavBar/NavBar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCol: typeof import('naive-ui')['NCol']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NRow: typeof import('naive-ui')['NRow']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
